config/routes.rb
Rails.application.routes.draw do
	resources :ordered_products
  	resources :products
  	resources :orders
  	devise_for :users, :controllers => { registrations: 'registrations'}
  	root 'products#index', as: 'home'
  	get '/profile', to: 'users#profile'

  	namespace :users do
  		resources :orders, only: [:index, :show]
  	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user, optional: true
	has_many :ordered_products, :dependent => :destroy
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :ordered_product, :dependent => :destroy
	mount_uploader :picture, PictureUploader
  #validates :title, :brand, :price, :model, presence: true
  #validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  #validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed" }
  #validates :price, numericality: { only_integer: true }, length: { maximum: 7 }

end

app/models/user.rb
class User < ApplicationRecord
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :phone,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_order

	def set_current_order
		# session["current_order_id"] = nil
		current_user_id = nil
		if !current_user.nil?
			current_user_id = current_user.id
		end
		if session["current_order_id"]
			@current_order = Order.find(session["current_order_id"])
			if (@current_order.status != "draft")
				@current_order = Order.create(status: "draft")
				session["current_order_id"] = @current_order.id
			end
		else
			@current_order = Order.create(status: "draft")
			session["current_order_id"] = @current_order.id
		end
	end
end

app/controllers/concerns/current_cart.rb
module CurrentCart

  private

    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

end

app/controllers/ordered_products_controller.rb
class OrderedProductsController < ApplicationController
	def index
		@total_price = 0
		@current_order.ordered_products.each do |ordered_product|
			@total_price += ordered_product.price
		end
	end
	def new
		@productsIdArray ||= []
		@current_order.ordered_products.each do |ordered_product|
			@productsIdArray.push(ordered_product.product.id.to_s)
		end
		if @productsIdArray.include?(params[:product_id])

			@orderedProduct = OrderedProduct.find_by(
				product_id: params[:product_id], 
				order_id: @current_order.id)

			@amount = params[:amount].to_i

			@orderedProduct.update_attributes(
				:amount => (@orderedProduct.amount + @amount), 
				:price => @orderedProduct.product.price * (@orderedProduct.amount + @amount))
			redirect_to products_path
		else
			@orderedProduct = OrderedProduct.create(product_id: params[:product_id], 
				order_id: @current_order.id, 
				amount: params[:amount])
			@orderedProduct.update_attributes(
				:price => @orderedProduct.product.price * @orderedProduct.amount)
			@orderedProduct.save
			redirect_to products_path
		end
	end
	def destroy
		@ordered_product = OrderedProduct.find(params[:id])
		@ordered_product.destroy
		redirect_to ordered_products_path
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def update
		current_user_id = nil
		if !current_user.nil?
			current_user_id = current_user.id
		end
		if (params[:order][:status] == 'created')
			@current_order.update_attributes(:status => params[:order][:status], :user_id => current_user_id)
			redirect_to ordered_products_path
		end

		if (params[:order][:status] == 'canceled')
			@order = Order.find(params[:id])
			@order.update_attributes(:status => params[:order][:status])
			redirect_to users_orders_path
		end
	end

	private 
	def post_params
		params.require(:current_order).permit(:status)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy]
  	before_action :authenticate_user!, except: [:index, :show]
	def index
		@product = Product.all
	end

	def show
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(post_params)

		if @product.save
			redirect_to @product
		else
			render :new
		end
	end

	def destroy
		@product.destroy
		redirect_to products_path
	end

	def edit
	end

	def update
		if @product.update_attributes(post_params)
			redirect_to @product
		else
			render :edit
		end
	end


	private 

	def set_product
      @product = Product.find(params[:id])
    end

	def post_params
		params.require(:product).permit(:category, :title, :description, :price, :picture)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation, :phone)
	end

	def account_update_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation, :current_password, :phone)
	end
end

app/controllers/users/orders_controller.rb
module Users
	class OrdersController < ApplicationController
		def show
			@order = Order.find(params[:id])
		end

		def index
			
		end
	end
end

# /users/orders

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def profile
  	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cart_count_over_one
    if @cart.line_items.count > 0
      return "<span class='tag is-dark'>#{@cart.line_items.count}</span>".html_safe
    end
  end

  def cart_has_items
    return @cart.line_items.count > 0
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/ordered_products_helper.rb
module OrderedProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CourseWork
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css'
  body[style="background: #fff3e0"]
    .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-5.text-white.border[style="background: #3F729B; box-shadow: 0 0 15px rgba(0, 0, 0, 0.5)"]
      h1.my-0.mr-md-auto.font-weight-bold
        | MuzMagaz
      nav.my-2.my-md-0.mr-md-3
        h4
          = link_to 'На главную',home_path, class: "p-2 text-white"
      h2
        = link_to ordered_products_path, class: "btn btn-outline-warning text-white"
          i.fa.fa-shopping-cart
          |  Корзина
      - if user_signed_in?
        h2
          = link_to profile_path, class: "btn btn-outline-warning text-white"
            i.fa.fa-user
            |  
            = current_user.username
        h2
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary text-white"
      - else
        h2
          = link_to 'Зарегистрироваться', new_user_registration_path, class: "btn btn-outline-primary text-white"
        h2
          = link_to 'Войти', new_user_session_path, class: "btn btn-outline-primary text-white"
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/ordered_products/index.html.slim
span
  h1
    | Корзина
div
  p
    = link_to 'К списку продуктов', products_path, class: "btn btn-outline-primary"
- unless @current_order.ordered_products.blank?
  - @current_order.ordered_products.each do |ordered_product|
    .card.border-info.mb-3
      .card-header
        .row
          h2.col-md-8.text-center
            = ordered_product.product.title
          h3.col-md-2.text-center
            | Кол-во: 
            = ordered_product.amount
          h3.col-md-2.text-center
            = link_to 'удалить', ordered_product_path(ordered_product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

      .card-body
        .card-text.text-center
          = image_tag(ordered_product.product.picture.thumb.url, alt: 'Image') if ordered_product.product.picture?
        h5.card-subtitle.mb-2.text-muted.text-center
          = ordered_product.product.description.truncate(100)
        h3.card-text.text-center
          = number_to_currency(ordered_product.product.price, locale: :ru)
        .text-right
          p
            = link_to 'подробнее', ordered_product.product, class: "btn btn-outline-primary"

      .card-footer
        p.text-muted
          | Добавлен 
          = ordered_product.created_at.strftime('%F')
        h3.text-right
          | Цена:  
          = number_to_currency(ordered_product.price, locale: :ru)
  hr
  h1
    | Итого: 
    = number_to_currency(@total_price, locale: :ru)
  = form_for @current_order do |form|
    = form.hidden_field :status, :value => "created"
    = form.submit("Оформить заказ",{:class => 'btn btn-primary btn-lg'})
  br
  br
- else
  h5.text-center
    |  Корзина пуста :( 
  .text-center
    = link_to products_path, class: "btn btn-success btn-lg text-white"
      i.fa.fa-cart-plus  
      |  добавить товары в корзину

app/views/products/_productForm.html.slim
= form_for @product do |form|
  - if product.errors.any?
    #error_explanation
      h2
        = pluralize(product.errors.count, "error")
        |  prohibited this product from being saved:
      ul
        - product.errors.full_messages.each do |message|
          li
            = message
  div
    label
      | Тип
    div
      = form.text_field(:category, {:class => 'form-control'})
    label
      | Название
    div
      = form.text_field(:title, {:class => 'form-control'})
    label
      | Описание
    div
      = form.text_area(:description, {:class => 'form-control'})
    label
      | Цена
    div
      = form.text_field(:price, {:class => 'form-control'})
    div
      = form.file_field(:picture, {:class => 'form-control'})
    br
    div
      = form.submit("Готово",{:class => 'btn btn-primary btn-lg'})

app/views/products/index.html.slim
span
  h1
    | Товары
- @product.each do |product|
  .card.border-info.mb-10
    .card-header
      .row
        span.col-md-3.text-center
          .alert.alert-success.border.rounded
            = product.category
        h2.col-md-7.text-center
          = product.title
    .card-body
      .card-text.text-center
        = image_tag(product.picture.thumb.url, alt: 'Image') if product.picture?
      h5.card-subtitle.mb-2.text-muted.text-center
        = product.description.truncate(100)
      h3.card-text.text-center
        = number_to_currency(product.price, locale: :ru)
      .text-right
        p
          = link_to 'подробнее', product, class: "btn btn-outline-primary"

    .card-footer.text-muted
      .row
        div.align-self-center.col-md-1
          | Кол-во: 
        div.col-md-11
          = form_with url: new_ordered_product_path, method: :get, local: true do |form|
            = form.hidden_field :product_id, :value => product.id
            = form.number_field :amount, :value => 1, :in => 1...11
            = form.submit("В корзину", {:class => 'btn btn-primary btn-lg'})
  br

app/views/products/new.html.slim
h1
  | Новый товар
= render 'productForm', product: @product

app/views/products/show.html.slim
p
  = link_to 'К списку продуктов', products_path, class: "btn btn-outline-primary"
.card.border-info.mb-3
  .card-header
    .row
      span.col-md-3.text-center
        .alert.alert-success.border.rounded
          = @product.category
      h2.col-md-7.text-center
        = @product.title
  .card-body
    .card-text.text-center
      = image_tag(@product.picture.thumb.url, alt: 'Image') 
    h5.card-subtitle.mb-2.text-muted
      = @product.description
    h3.card-text.text-center
      = number_to_currency(@product.price, locale: :ru)
  .card-footer.text-muted
    .row
      div.p.col-md-1.text-center
        | Кол-во: 
      div.col-md-5
        = form_with url: new_ordered_product_path, method: :get, local: true do |form|
          = form.hidden_field :product_id, :value => @product.id
          = form.number_field :amount, :value => 1
          = form.submit("В корзину", {:class => 'btn btn-primary btn-lg col-md-4'})

app/views/users/orders/index.html.slim
span
  h1
    | История заказов
  br
- unless current_user.orders.blank?
  - current_user.orders.order("created_at DESC").each do |order|
    - if (order.status != 'draft')
      .card.border-info.mb-3
        .card-header
          .row
            div.col-md-2.text-center
              | Заказ № 
              = order.id           
            - if (order.status == 'created')
                h4.col-md-7.text-center
                  div.alert.alert-info.border.rounded
                    | заказ в обработке
                h5.col-md-1.text-center
                  div          
                    = form_for order, :action => "update" do |form|
                      = form.hidden_field :status, :value => "canceled"
                      = form.submit("Отменить заказ",{:class => 'btn btn-danger btn-lg'})
            - if (order.status == 'in_progress')
                h4.col-md-10.text-center
                  div.alert.alert-warning.border.rounded
                    | заказ в пути
                
            - if (order.status == 'completed')
                h4.col-md-10.text-center
                  div.alert.alert-success.border.rounded
                    | заказ доставлен
            - if (order.status == 'canceled')
                h4.col-md-10.text-center
                  div.alert.alert-dark.border.rounded
                    | заказ отменён
        .card-body
          - @total_price = 0
          - order.ordered_products.each do |ordered_product|
              span.card-text.text-left 
                = ordered_product.product.title
                |  - 
                = ordered_product.amount
                |  шт., 
                = number_to_currency(ordered_product.price, locale: :ru)
                - @total_price += ordered_product.price
                br
        .text-right
          p
            = link_to 'посмотреть товары', users_order_path(id: order.id), class: "btn btn-outline-primary"
          div.alert.alert-secondary.border.rounded           
            h3
              | Итого: 
              = number_to_currency(@total_price, locale: :ru)

        .card-footer.text-muted
          p
            | создан 
            = order.created_at.strftime('%F')
- else
  |  У вас еще нет заказов :( 
  p
    = link_to 'добавить товары в корзину', products_path, class: "btn btn-outline-primary"

app/views/users/orders/show.html.slim
= link_to "Назад к истории", users_orders_path, class: "btn btn-warning text-white"

- unless @order.ordered_products.blank?
  - @order.ordered_products.each do |ordered_product|
    .card.border-info.mb-3
      .card-header
        .row
          div.col-md-2.text-center
              | Заказ № 
              = ordered_product.order_id
          h2.col-md-8.text-center
            = ordered_product.product.title
          h3.col-md-2.text-center
            | Кол-во: 
            = ordered_product.amount

      .card-body
      	.card-text.text-center
        	= image_tag(ordered_product.product.picture.thumb.url, alt: 'Image') if ordered_product.product.picture?
        h5.card-subtitle.mb-2.text-muted.text-center
          = ordered_product.product.description.truncate(100)
        h3.card-text.text-center
          = number_to_currency(ordered_product.product.price, locale: :ru)
        .text-right
          p
            = link_to 'подробнее', ordered_product.product, class: "btn btn-outline-primary"

      .card-footer.text-muted
        p
          | Добавлен 
          = ordered_product.created_at.strftime('%F')
- else
  |  Некорректный заказ :(

app/views/users/profile.html.slim
div.bg-light.text-center.border.border-primary.rounded
	h1
	  | Мой профиль
br

h2.text-right
    = link_to "Изменить данные профиля", edit_user_registration_path, class: "btn btn-warning text-white"

h2.text-right
    = link_to "История заказов", users_orders_path, class: "btn btn-warning text-white"
.span
	.h3
		| Имя пользователя: 
		= current_user.username
	.h3
		| email: 
		= current_user.email

	.h3
		| Номер телефона: 
		= current_user.phone